FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y nodejs git npm

RUN git clone https://github.com/ReactFinland/graphql-api.git

WORKDIR /graphql-api

RUN npm install