services: 

  react-finland:
    build:
      context: ./../..
      dockerfile: ./targets/react-finland/Dockerfile.react-finland
    container_name: react_finland
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "production"
    command: sh -c "timeout 60 npm start"
  clairvoyance:
    build:
      context: ./../..
      dockerfile: ./targets/react-finland/Dockerfile.clairvoyance
    depends_on:
      - react-finland
    command: ./react-finland.sh && docker stop react_finland
    volumes:
      - ../../results/react-finland:/results

volumes:
  mydata: