type Query {
  people: Contact
  locations: Location
  conferences: Conference
  sponsors: Contact
  allSeries: Series
  themes: Theme
  series(id: ID!): Series
  theme(conferenceId: ID!): Theme
  conference(id: ID!): Conference
  schedule(conferenceId: ID!, day: String!): Schedule
  contact(conferenceId: ID!, contactName: String!): Contact
  interval(conferenceId: ID!, intervalTitle: String!): Interval
  allConferences: Conference
}

type Contact {
  aboutShort: String
  keywords: [String!]
  name: String!
  noPhotography: Boolean
  tagline: String
  company: String
  about: String!
  lastName: String!
  firstName: String!
  image: Image
  country: Country
  talks: Session
  workshops: Session
  social: Social
  location: Location
  type: [ContactType!]!
}

type Location {
  about: String
  city: String
  address: String
  name: String
  country: Country
  social: Social
  image: Image
}

type Conference {
  endDate: String!
  name: String!
  id: ID!
  year: String!
  startDate: String!
  websiteUrl: String!
  slogan: String!
  speakers: Contact
  schedules: Schedule
  series: Series
  locations: Location
  workshopInstructors: Contact
  lightningTalks: Session
  platformSponsors: Contact
  silverSponsors: Contact
  mcs: Contact
  goldSponsors: Contact
  partners: Contact
  organizer: Contact
  keynotes: Session
  attendees: Contact
  talks: Session
  workshops: Session
  sponsors: Contact
  fullTalks: Session
  bronzeSponsors: Contact
  organizers: Contact
  allSpeakers: Contact
}

type Series {
  name: String!
  id: ID!
  conferences: Conference
}

type Theme {
  id: ID!
  colors: Colors
  textures: Image
  fonts: Fonts
  logos: Logos
}

type Schedule {
  day: String!
  description: String
  intervals: Interval
  location: Location
}

type Interval {
  begin: String!
  end: String!
  drawing: String
  title: String
  urls: SessionUrls
  location: Location
  mc: Contact
  sessions: Session
}

type Image {
  title: String
  url: String!
  style: Style
}

type Country {
  code: String!
  name: String!
}

type Session {
  begin: String
  end: String
  hasTitle: Boolean!
  title: String!
  day: String
  description: String
  keywords: [String!]
  people: Contact
  speakers: Contact
  urls: SessionUrls
  parent: Interval
  sessions: Session
  location: Location
  type: SessionType!
  level: Level!
}

type Social {
  linkedin: String
  twitter: String
  facebook: String
  pinterest: String
  vk: String
  googleMaps: String
  youtube: String
  twitch: String
  tiktok: String
  homepage: String
  devto: String
  mastodon: String
  medium: String
  github: String
  bluesky: String
  instagram: String
  dribble: String
  vimeo: String
}

type ContactType {
  dummy: String
}

type Colors {
  text: String!
  primary: String!
  secondary: String!
  background: String!
}

type Fonts {
  secondary: String!
  primary: String!
  variants: Font
}

type Logos {
  black: WithWithoutText
  white: WithWithoutText
  colored: WithWithoutText
}

type SessionUrls {
  web: String
  slides: String
  drawing: String
  demo: String
  video: String
}

type Style {
  backgroundSize: String!
}

type SessionType {
  dummy: String
}

type Level {
  dummy: String
}

type Font {
  formats: [String!]
  href: String
  fileName: String
  weight: String
  style: String
  family: String
}

type WithWithoutText {
  withText: Image
  withoutText: Image
}