[tool.poetry]
name = "KrakQL"
version = "1.0.0"
description = "Obtain GraphQL API Schema even if the introspection is not enabled (LLM-powered)"
authors = [
    "ANONYMOUS AUTHORS"
]
maintainers = [
    "ANONYMOUS AUTHORS"
]
license = "Apache-2.0"
packages = [
    { include = "krakql" }
]
readme = "README.md"
#"homepage" = "https://github.com/nikitastupin/clairvoyance"
#"repository" = "https://github.com/nikitastupin/clairvoyance"

[tool.poetry.scripts]
krakql = 'krakql:cli'

[tool.coverage.run]
omit = [
    'tests/*',
    'examples/*',
    'docs/*',
]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
google-adk = "^1.9.0"
google-genai= "^1.28.0"
aiohttp = {extras = ["speedups"], version = "^3.12.15"}
asyncio = "^3.4.3"
rich = "^14.1.0"
litellm = "^1.74.15"
graphql-core = "^3.2.6"
