services:
  mysql:
    platform: linux/amd64
    image: mysql:9.3.0-oraclelinux9
    container_name: poke-gql_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pokedb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u$$MYSQL_USER", "-p$$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  poke-gql:
    platform: linux/amd64
    image: poke-gql
    build:
      dockerfile: ./Dockerfile
    ports:
      - ":4000"
    command: sh -c "cd /poke-db && node src/db/index.js  && cd /poke-gql && npm start"
    environment:
      DB_HOST: mysql
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_NAME: pokedb
    depends_on:
      mysql:
        condition: service_healthy

