services: 

  react-finland:
    build:
      dockerfile: ./Dockerfile
    image:
      react-finland
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "production"
    command: sh -c "timeout 60 npm start"