FROM ubuntu:22.04

# Install dependencies
RUN apt-get update

# Install Python
RUN apt-get install -y python3-pip

# Install Clairvoyance
# TODO: replace with local installation
RUN pip3 install clairvoyance==2.5.2