services: 
  petclinic_graphql_db:
    image: postgres:16.1-alpine
    command: ["postgres", "-c", "log_statement=all"]
    container_name: petclinic_graphql_db
    environment:
      - POSTGRES_PASSWORD=secretpw
      - POSTGRES_USER=klaus
      - POSTGRES_DB=petclinic_graphql_db
      - POSTGRES_INITDB_ARGS=--locale-provider=icu --icu-locale=en
  petclinic-graphql:
    platform: linux/amd64
    image: petclinic-graphql
    depends_on:
      - petclinic_graphql_db
    build:
      dockerfile: ./Dockerfile
    ports:
      - ":9977"
    command: ./build-local.sh