type Query {
  people: Contact
  sponsors: Contact
  themes: Theme
  allConferences: Conference
  conferences: Conference
  locations: Location
  series(id: ID!): Series
  conference(id: ID!): Conference
  theme(conferenceId: ID!): Theme
  contact(conferenceId: ID!, contactName: String!): Contact
  schedule(conferenceId: ID!, day: String!): Schedule
  interval(conferenceId: ID!, intervalTitle: String!): Interval
  allSeries: Series
}

type Contact {
  keywords: [String!]
  firstName: String!
  tagline: String
  aboutShort: String
  noPhotography: Boolean
  name: String!
  company: String
  about: String!
  lastName: String!
  social: Social
  workshops: Session
  talks: Session
  country: Country
  image: Image
  location: Location
  type: [ContactType!]!
}

type Theme {
  id: ID!
  textures: Image
  logos: Logos
  colors: Colors
  fonts: Fonts
}

type Conference {
  year: String!
  startDate: String!
  endDate: String!
  name: String!
  id: ID!
  websiteUrl: String!
  slogan: String!
  mcs: Contact
  keynotes: Session
  sponsors: Contact
  goldSponsors: Contact
  series: Series
  fullTalks: Session
  speakers: Contact
  platformSponsors: Contact
  locations: Location
  partners: Contact
  workshopInstructors: Contact
  organizer: Contact
  organizers: Contact
  lightningTalks: Session
  bronzeSponsors: Contact
  attendees: Contact
  allSpeakers: Contact
  workshops: Session
  talks: Session
  silverSponsors: Contact
  schedules: Schedule
}

type Location {
  city: String
  name: String
  address: String
  about: String
  social: Social
  country: Country
  image: Image
}

type Series {
  name: String!
  id: ID!
  conferences: Conference
}

type Schedule {
  description: String
  day: String!
  location: Location
  intervals: Interval
}

type Interval {
  drawing: String
  begin: String!
  end: String!
  title: String
  urls: SessionUrls
  mc: Contact
  sessions: Session
  location: Location
}

type Social {
  bluesky: String
  vk: String
  linkedin: String
  googleMaps: String
  vimeo: String
  twitch: String
  mastodon: String
  devto: String
  instagram: String
  twitter: String
  github: String
  medium: String
  youtube: String
  homepage: String
  pinterest: String
  facebook: String
  dribble: String
  tiktok: String
}

type Session {
  keywords: [String!]
  hasTitle: Boolean!
  begin: String
  end: String
  day: String
  title: String!
  description: String
  level: Level!
  people: Contact
  urls: SessionUrls
  type: SessionType!
  speakers: Contact
  parent: Interval
  sessions: Session
  location: Location
}

type Country {
  code: String!
  name: String!
}

type Image {
  title: String
  url: String!
  style: Style
}

type ContactType {
  dummy: String
}

type Logos {
  black: WithWithoutText
  white: WithWithoutText
  colored: WithWithoutText
}

type Colors {
  background: String!
  text: String!
  secondary: String!
  primary: String!
}

type Fonts {
  secondary: String!
  primary: String!
  variants: Font
}

type SessionUrls {
  slides: String
  drawing: String
  web: String
  video: String
  demo: String
}

type Level {
  dummy: String
}

type SessionType {
  dummy: String
}

type Style {
  backgroundSize: String!
}

type WithWithoutText {
  withoutText: Image
  withText: Image
}

type Font {
  href: String
  formats: [String!]
  family: String
  fileName: String
  weight: String
  style: String
}