services:
  db:
    platform: linux/amd64
    image: postgres:13
    environment:
      POSTGRES_DB: patio
      POSTGRES_USER: patio
      POSTGRES_PASSWORD: yourpassword
    networks:
      - patio-network

  patio-api:
    platform: linux/amd64
    image: patio-api
    build:
      dockerfile: ./Dockerfile
    depends_on:
      - db
    environment:
      PATIO_JDBC_URL: "jdbc:postgresql://db:5432/patio"
      PATIO_JDBC_USER: "patio"
      PATIO_JDBC_PASSWORD: "yourpassword"
      PATIO_JDBC_DRIVER: "org.postgresql.Driver"
      PATIO_JWT_SECRET: "mysupersecret"
      PATIO_JWT_ALGO: "HS256"
      PATIO_JWT_ISSUER: "patio"
      PATIO_JWT_DAYS: 7
      #PATIO_OAUTH2_KEY: ""
      #PATIO_OAUTH2_SECRET: ""
      #PATIO_OAUTH2_CALLBACK: ""
      PATIO_DUSER_ENABLED: true
      PATIO_DUSER_NAME: "username"
      PATIO_DUSER_EMAIL: "username@default.com"
      PATIO_DUSER_PASSWORD: "password"
    networks:
      - patio-network
    ports:
      - ":8080"
    command: ./gradlew run
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/graphql"]
      interval: 1m
      timeout: 5s
      retries: 3
networks:
  patio-network:
    driver: bridge
