FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install git -y
RUN apt-get install -y nodejs npm
RUN git clone https://github.com/trevorblades/countries.git
WORKDIR /country