services:
  country:
    build:
      context: ./../..
      dockerfile: ./targets/country/Dockerfile.country
    ports:
      - "8787:8787"
    command: ./npm start && exit 0
  clairvoyance:
    build:
      context: ./../..
      dockerfile: ./targets/country/Dockerfile.clairvoyance
    depends_on:
      - country
    command: ./country.sh && docker stop country
    volumes:
      - ./results:/results
